### ISSUE TITLE
Submit button: Uncaught ReferenceError: checkOptions is not defined

### ISSUE THREAD

**Issue by hederacea** [irudnyts/jsquiz#13]
Hi - thankyou for writing this -
I'm not sure if I haven't installed something correctly (I have run the init() and the js files have appeared in the main bookdown folder with the Rmd files), I'm getting this error:

Uncaught ReferenceError: checkOptions is not defined
    at HTMLButtonElement.onclick

So although the quiz question appears fine, nothing happens when the submit button is clicked, so I'm not sure if I was meant to load/call the js or something.

**Comment by irudnyts** [comment]
There are two places where things can go wrong. You need to make sure that:
1/ `javascript.html` is in the root (i.e., `.Rmd` files live)
2/ `javascript.html` is included in `_output.yml`. The beginning of this file should look something like this: 

```
bookdown::gitbook:
  includes:
    in_header: javascript.html
...
``` 

If it still does not work, pls let me know :)

**Comment by hederacea** [comment]
Thankyou - my oversight, I'm using the bs4_book format and didn't put the in_header information in (I honestly completely missed it). It works now! Thanks again for making this available, nice easy way to add little check points into my lecture notes.
